export const FETCH_DICTATIONS = 'FETCH_DICTATIONS';
export const RECEIVE_DICTATIONS = 'RECEIVE_DICTATIONS';
export const RECEIVE_DICTATIONS_ERROR = 'RECEIVE_DICTATIONS_ERROR';

export const UPDATE_DICTATION = 'UPDATE_DICTATION';
export const UPDATE_DICTATION_SUCCESS = 'UPDATE_DICTATION_SUCCESS';
export const UPDATE_DICTATION_ERROR = 'UPDATE_DICTATION_ERROR';


export const CREATE_DICTATION = 'CREATE_DICTATION';
export const CREATE_DICTATION_SUCCESS = 'CREATE_DICTATION_SUCCESS';
export const CREATE_DICTATION_ERROR = 'CREATE_DICTATION_ERROR';